# Generated by Django 4.2.7 on 2024-02-28 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date_added',
        ),
    ]
