# Generated by Django 4.2.7 on 2024-02-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='total',
            field=models.CharField(default='50', max_length=1000),
            preserve_default=False,
        ),
    ]
