# Generated by Django 4.2.7 on 2024-03-13 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_client_options_remove_client_adress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos')),
                ('nom', models.CharField(default='', max_length=100)),
                ('prenom', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('pays', models.CharField(default='', max_length=300)),
                ('ville', models.CharField(default='', max_length=300)),
                ('adresse', models.CharField(default='', max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
